
#Number of maximum reccursive attempts - when there are commands (types 1, 2 and 3) inside commands.
recursive_attempts: 3


# \emph{} like
type_1: ["emph", "textit", "textbf", "rev", "url", "section", "subsection", "subsubsection", "chapter"]

# \color{blue} like
type_2: ["color", "label", "vspace", "hspace"]

# \textcolor{blue}{} like
type_3: ["textcolor"]

# \noindent like
type_4: ["noindent", "QEDA", "QEDB", "item"]


# \begin{equation} \end{equation} like
type_5: ["equation", "eqnarray", "comment", "subequations", "figure", "algorithm", "table", "tabular"]

# \begin{definition} \end{equation} like
type_6: ["definition", "lemma", "theorem", "proof", "enumerate", "itemize", "lstlisting", "center"]



#Hilight if one of these strings are left on the text
residues: ["\\","/", "{", "}", "'", "`"]